/*
 * SIMD versions of sha1dc's ubc_check: each vector lane checks the
 * unavoidable bit conditions of one 64-byte block. One block is clean
 * (needs no recompression checks) iff its dvmask lane is zero.
 *
 * Generated by gen_ubc_simd.py from ubc_check.c. Do not edit.
 * Regenerate with:
 *   python3 lib/gen_ubc_simd.py lib/ubc_check.c 4 --header 8 --tst
 *   python3 lib/gen_ubc_simd.py lib/ubc_check.c 8 --header 8
 *   python3 lib/gen_ubc_simd.py lib/ubc_check.c 16 --header 8
 * (--tst is the NEON-friendly style used by the aarch64 fast path; the
 * 8/16-lane sections keep the shift style that AVX2/AVX-512 prefer.)
 */
#ifndef SHA1DC_UBC_CHECK_SIMD_H
#define SHA1DC_UBC_CHECK_SIMD_H
/* Generated by gen_ubc_simd.py from ubc_check.c (4 lanes). Do not edit. */
#ifndef UBC_CHECK_V4_H
#define UBC_CHECK_V4_H
#include <stdint.h>

typedef uint32_t u32v4 __attribute__((vector_size(16)));

static inline __attribute__((always_inline)) int ubc_v4_all_zero(const u32v4 *v)
{
	uint32_t a = 0;
	int i;
	for (i = 0; i < 4; i++)
		a |= (*v)[i];
	return a == 0;
}

#ifndef SHA1DC_UBC_DV_BITS
#define SHA1DC_UBC_DV_BITS
static const uint32_t DV_I_43_0_bit 	= (uint32_t)(1) << 0;
static const uint32_t DV_I_44_0_bit 	= (uint32_t)(1) << 1;
static const uint32_t DV_I_45_0_bit 	= (uint32_t)(1) << 2;
static const uint32_t DV_I_46_0_bit 	= (uint32_t)(1) << 3;
static const uint32_t DV_I_46_2_bit 	= (uint32_t)(1) << 4;
static const uint32_t DV_I_47_0_bit 	= (uint32_t)(1) << 5;
static const uint32_t DV_I_47_2_bit 	= (uint32_t)(1) << 6;
static const uint32_t DV_I_48_0_bit 	= (uint32_t)(1) << 7;
static const uint32_t DV_I_48_2_bit 	= (uint32_t)(1) << 8;
static const uint32_t DV_I_49_0_bit 	= (uint32_t)(1) << 9;
static const uint32_t DV_I_49_2_bit 	= (uint32_t)(1) << 10;
static const uint32_t DV_I_50_0_bit 	= (uint32_t)(1) << 11;
static const uint32_t DV_I_50_2_bit 	= (uint32_t)(1) << 12;
static const uint32_t DV_I_51_0_bit 	= (uint32_t)(1) << 13;
static const uint32_t DV_I_51_2_bit 	= (uint32_t)(1) << 14;
static const uint32_t DV_I_52_0_bit 	= (uint32_t)(1) << 15;
static const uint32_t DV_II_45_0_bit 	= (uint32_t)(1) << 16;
static const uint32_t DV_II_46_0_bit 	= (uint32_t)(1) << 17;
static const uint32_t DV_II_46_2_bit 	= (uint32_t)(1) << 18;
static const uint32_t DV_II_47_0_bit 	= (uint32_t)(1) << 19;
static const uint32_t DV_II_48_0_bit 	= (uint32_t)(1) << 20;
static const uint32_t DV_II_49_0_bit 	= (uint32_t)(1) << 21;
static const uint32_t DV_II_49_2_bit 	= (uint32_t)(1) << 22;
static const uint32_t DV_II_50_0_bit 	= (uint32_t)(1) << 23;
static const uint32_t DV_II_50_2_bit 	= (uint32_t)(1) << 24;
static const uint32_t DV_II_51_0_bit 	= (uint32_t)(1) << 25;
static const uint32_t DV_II_51_2_bit 	= (uint32_t)(1) << 26;
static const uint32_t DV_II_52_0_bit 	= (uint32_t)(1) << 27;
static const uint32_t DV_II_53_0_bit 	= (uint32_t)(1) << 28;
static const uint32_t DV_II_54_0_bit 	= (uint32_t)(1) << 29;
static const uint32_t DV_II_55_0_bit 	= (uint32_t)(1) << 30;
static const uint32_t DV_II_56_0_bit 	= (uint32_t)(1) << 31;
#endif /* SHA1DC_UBC_DV_BITS */

#ifndef SHA1DC_UBC_INLINE
#define SHA1DC_UBC_INLINE static inline __attribute__((always_inline))
#endif

SHA1DC_UBC_INLINE void ubc_check_v4_part0(const u32v4 W[65], u32v4 m[4])
{
	m[0] &= ~((u32v4)((((W[44]^W[45])) & (1u<<29)) != 0) & (DV_I_48_0_bit|DV_I_51_0_bit|DV_I_52_0_bit|DV_II_45_0_bit|DV_II_46_0_bit|DV_II_50_0_bit|DV_II_51_0_bit));
	m[1] &= ~((u32v4)((((W[49]^W[50])) & (1u<<29)) != 0) & (DV_I_46_0_bit|DV_II_45_0_bit|DV_II_50_0_bit|DV_II_51_0_bit|DV_II_55_0_bit|DV_II_56_0_bit));
	m[2] &= ~((u32v4)((((W[48]^W[49])) & (1u<<29)) != 0) & (DV_I_45_0_bit|DV_I_52_0_bit|DV_II_49_0_bit|DV_II_50_0_bit|DV_II_54_0_bit|DV_II_55_0_bit));
	m[3] &= ~((u32v4)((((W[47]^(W[50]>>25))) & (1u<<4)) != 0) & (DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_51_0_bit|DV_II_56_0_bit));
	m[0] &= ~((u32v4)((((W[47]^W[48])) & (1u<<29)) != 0) & (DV_I_44_0_bit|DV_I_51_0_bit|DV_II_48_0_bit|DV_II_49_0_bit|DV_II_53_0_bit|DV_II_54_0_bit));
	m[1] &= ~((u32v4)(((((W[46]>>4)^(W[49]>>29))) & (1u<<0)) != 0) & (DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit|DV_II_50_0_bit|DV_II_55_0_bit));
	m[2] &= ~((u32v4)((((W[46]^W[47])) & (1u<<29)) != 0) & (DV_I_43_0_bit|DV_I_50_0_bit|DV_II_47_0_bit|DV_II_48_0_bit|DV_II_52_0_bit|DV_II_53_0_bit));
	m[3] &= ~((u32v4)(((((W[45]>>4)^(W[48]>>29))) & (1u<<0)) != 0) & (DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit|DV_II_49_0_bit|DV_II_54_0_bit));
	m[0] &= ~((u32v4)((((W[45]^W[46])) & (1u<<29)) != 0) & (DV_I_49_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_47_0_bit|DV_II_51_0_bit|DV_II_52_0_bit));
	m[1] &= ~((u32v4)(((((W[44]>>4)^(W[47]>>29))) & (1u<<0)) != 0) & (DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit|DV_II_48_0_bit|DV_II_53_0_bit));
	m[2] &= ~((u32v4)(((((W[43]>>4)^(W[46]>>29))) & (1u<<0)) != 0) & (DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit|DV_II_47_0_bit|DV_II_52_0_bit));
	m[3] &= ~((u32v4)((((W[43]^W[44])) & (1u<<29)) != 0) & (DV_I_47_0_bit|DV_I_50_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_49_0_bit|DV_II_50_0_bit));
	m[0] &= ~((u32v4)(((((W[42]>>4)^(W[45]>>29))) & (1u<<0)) != 0) & (DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_51_0_bit));
	m[1] &= ~((u32v4)(((((W[41]>>4)^(W[44]>>29))) & (1u<<0)) != 0) & (DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_50_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v4_part1(const u32v4 W[65], u32v4 m[4])
{
	m[2] &= ~((u32v4)((((W[40]^W[41])) & (1u<<29)) != 0) & (DV_I_44_0_bit|DV_I_47_0_bit|DV_I_48_0_bit|DV_II_46_0_bit|DV_II_47_0_bit|DV_II_56_0_bit));
	m[3] &= ~((u32v4)((((W[54]^W[55])) & (1u<<29)) != 0) & (DV_I_51_0_bit|DV_II_47_0_bit|DV_II_50_0_bit|DV_II_55_0_bit|DV_II_56_0_bit));
	m[0] &= ~((u32v4)((((W[53]^W[54])) & (1u<<29)) != 0) & (DV_I_50_0_bit|DV_II_46_0_bit|DV_II_49_0_bit|DV_II_54_0_bit|DV_II_55_0_bit));
	m[1] &= ~((u32v4)((((W[52]^W[53])) & (1u<<29)) != 0) & (DV_I_49_0_bit|DV_II_45_0_bit|DV_II_48_0_bit|DV_II_53_0_bit|DV_II_54_0_bit));
	m[2] &= ~((u32v4)((((W[50]^(W[53]>>25))) & (1u<<4)) != 0) & (DV_I_50_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_48_0_bit|DV_II_54_0_bit));
	m[3] &= ~((u32v4)((((W[50]^W[51])) & (1u<<29)) != 0) & (DV_I_47_0_bit|DV_II_46_0_bit|DV_II_51_0_bit|DV_II_52_0_bit|DV_II_56_0_bit));
	m[0] &= ~((u32v4)((((W[49]^(W[52]>>25))) & (1u<<4)) != 0) & (DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_47_0_bit|DV_II_53_0_bit));
	m[1] &= ~((u32v4)((((W[48]^(W[51]>>25))) & (1u<<4)) != 0) & (DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_52_0_bit));
	m[2] &= ~((u32v4)((((W[42]^W[43])) & (1u<<29)) != 0) & (DV_I_46_0_bit|DV_I_49_0_bit|DV_I_50_0_bit|DV_II_48_0_bit|DV_II_49_0_bit));
	m[3] &= ~((u32v4)((((W[41]^W[42])) & (1u<<29)) != 0) & (DV_I_45_0_bit|DV_I_48_0_bit|DV_I_49_0_bit|DV_II_47_0_bit|DV_II_48_0_bit));
	m[0] &= ~((u32v4)(((((W[40]>>4)^(W[43]>>29))) & (1u<<0)) != 0) & (DV_I_44_0_bit|DV_I_46_0_bit|DV_I_50_0_bit|DV_II_49_0_bit|DV_II_56_0_bit));
	m[1] &= ~((u32v4)(((((W[39]>>4)^(W[42]>>29))) & (1u<<0)) != 0) & (DV_I_43_0_bit|DV_I_45_0_bit|DV_I_49_0_bit|DV_II_48_0_bit|DV_II_55_0_bit));
	m[2] &= ~((u32v4)(((((W[38]>>4)^(W[41]>>29))) & (1u<<0)) != 0) & (DV_I_44_0_bit|DV_I_48_0_bit|DV_II_47_0_bit|DV_II_54_0_bit|DV_II_56_0_bit));
	m[3] &= ~((u32v4)(((((W[37]>>4)^(W[40]>>29))) & (1u<<0)) != 0) & (DV_I_43_0_bit|DV_I_47_0_bit|DV_II_46_0_bit|DV_II_53_0_bit|DV_II_55_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v4_part2(const u32v4 W[65], u32v4 m[4])
{
	m[0] &= ~((u32v4)((((W[55]^W[56])) & (1u<<29)) != 0) & (DV_I_52_0_bit|DV_II_48_0_bit|DV_II_51_0_bit|DV_II_56_0_bit));
	m[1] &= ~((u32v4)((((W[52]^(W[55]>>25))) & (1u<<4)) != 0) & (DV_I_52_0_bit|DV_II_48_0_bit|DV_II_50_0_bit|DV_II_56_0_bit));
	m[2] &= ~((u32v4)((((W[51]^(W[54]>>25))) & (1u<<4)) != 0) & (DV_I_51_0_bit|DV_II_47_0_bit|DV_II_49_0_bit|DV_II_55_0_bit));
	m[3] &= ~((u32v4)((((W[51]^W[52])) & (1u<<29)) != 0) & (DV_I_48_0_bit|DV_II_47_0_bit|DV_II_52_0_bit|DV_II_53_0_bit));
	m[0] &= ~((u32v4)(((((W[36]>>4)^(W[40]>>29))) & (1u<<0)) != 0) & (DV_I_46_0_bit|DV_I_49_0_bit|DV_II_45_0_bit|DV_II_48_0_bit));
	m[1] &= ~((u32v4)((((W[53]^W[56])) & (uint32_t)536870912u) == 0) & (DV_I_52_0_bit|DV_II_48_0_bit|DV_II_49_0_bit));
	m[2] &= ~((u32v4)((((W[51]^W[54])) & (uint32_t)536870912u) == 0) & (DV_I_50_0_bit|DV_II_46_0_bit|DV_II_47_0_bit));
	m[3] &= ~((u32v4)((((W[50]^W[52])) & (uint32_t)536870912u) == 0) & (DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit));
	m[0] &= ~((u32v4)((((W[49]^W[51])) & (uint32_t)536870912u) == 0) & (DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit));
	m[1] &= ~((u32v4)((((W[48]^W[50])) & (uint32_t)536870912u) == 0) & (DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit));
	m[2] &= ~((u32v4)((((W[47]^W[49])) & (uint32_t)536870912u) == 0) & (DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit));
	m[3] &= ~((u32v4)((((W[46]^W[48])) & (uint32_t)536870912u) == 0) & (DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit));
	m[0] &= ~((u32v4)((((W[45]^W[47])) & (1u<<6)) != 0) & (DV_I_47_2_bit|DV_I_49_2_bit|DV_I_51_2_bit));
	m[1] &= ~((u32v4)((((W[45]^W[47])) & (uint32_t)536870912u) == 0) & (DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v4_part3(const u32v4 W[65], u32v4 m[4])
{
	m[2] &= ~((u32v4)((((W[44]^W[46])) & (1u<<6)) != 0) & (DV_I_46_2_bit|DV_I_48_2_bit|DV_I_50_2_bit));
	m[3] &= ~((u32v4)((((W[44]^W[46])) & (uint32_t)536870912u) == 0) & (DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit));
	m[0] &= ~((u32v4)((((W[41]^(W[42]>>5))) & (uint32_t)2u) == 0) & (DV_I_48_2_bit|DV_II_46_2_bit|DV_II_51_2_bit));
	m[1] &= ~((u32v4)((((W[40]^(W[41]>>5))) & (uint32_t)2u) == 0) & (DV_I_47_2_bit|DV_I_51_2_bit|DV_II_50_2_bit));
	m[2] &= ~((u32v4)((((W[40]^W[42])) & (uint32_t)16u) == 0) & (DV_I_44_0_bit|DV_I_46_0_bit|DV_II_56_0_bit));
	m[3] &= ~((u32v4)((((W[39]^(W[40]>>5))) & (uint32_t)2u) == 0) & (DV_I_46_2_bit|DV_I_50_2_bit|DV_II_49_2_bit));
	m[0] &= ~((u32v4)((((W[39]^W[41])) & (uint32_t)16u) == 0) & (DV_I_43_0_bit|DV_I_45_0_bit|DV_II_55_0_bit));
	m[1] &= ~((u32v4)((((W[38]^W[40])) & (uint32_t)16u) == 0) & (DV_I_44_0_bit|DV_II_54_0_bit|DV_II_56_0_bit));
	m[2] &= ~((u32v4)((((W[37]^W[39])) & (uint32_t)16u) == 0) & (DV_I_43_0_bit|DV_II_53_0_bit|DV_II_55_0_bit));
	m[3] &= ~((u32v4)((((W[36]^(W[37]>>5))) & (uint32_t)2u) == 0) & (DV_I_47_2_bit|DV_I_50_2_bit|DV_II_46_2_bit));
	m[0] &= ~((u32v4)(((((W[35]>>4)^(W[39]>>29))) & (1u<<0)) != 0) & (DV_I_45_0_bit|DV_I_48_0_bit|DV_II_47_0_bit));
	m[1] &= ~((u32v4)((((W[63]^(W[64]>>5))) & (uint32_t)1u) == 0) & (DV_I_48_0_bit|DV_II_48_0_bit));
	m[2] &= ~((u32v4)((((W[63]^(W[64]>>5))) & (uint32_t)2u) == 0) & (DV_I_45_0_bit|DV_II_45_0_bit));
	m[3] &= ~((u32v4)((((W[62]^(W[63]>>5))) & (uint32_t)1u) == 0) & (DV_I_47_0_bit|DV_II_47_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v4_part4(const u32v4 W[65], u32v4 m[4])
{
	m[0] &= ~((u32v4)((((W[61]^(W[62]>>5))) & (uint32_t)1u) == 0) & (DV_I_46_0_bit|DV_II_46_0_bit));
	m[1] &= ~((u32v4)((((W[61]^(W[62]>>5))) & (uint32_t)4u) == 0) & (DV_I_46_2_bit|DV_II_46_2_bit));
	m[2] &= ~((u32v4)((((W[60]^(W[61]>>5))) & (uint32_t)1u) == 0) & (DV_I_45_0_bit|DV_II_45_0_bit));
	m[3] &= ~((u32v4)((((W[58]^W[59])) & (1u<<29)) != 0) & (DV_II_51_0_bit|DV_II_54_0_bit));
	m[0] &= ~((u32v4)((((W[57]^W[58])) & (1u<<29)) != 0) & (DV_II_50_0_bit|DV_II_53_0_bit));
	m[1] &= ~((u32v4)((((W[56]^(W[59]>>25))) & (1u<<4)) != 0) & (DV_II_52_0_bit|DV_II_54_0_bit));
	m[2] &= ~((u32v4)((((W[56]^W[59])) & (uint32_t)536870912u) == 0) & (DV_II_51_0_bit|DV_II_52_0_bit));
	m[3] &= ~((u32v4)((((W[56]^W[57])) & (1u<<29)) != 0) & (DV_II_49_0_bit|DV_II_52_0_bit));
	m[0] &= ~((u32v4)((((W[55]^(W[58]>>25))) & (1u<<4)) != 0) & (DV_II_51_0_bit|DV_II_53_0_bit));
	m[1] &= ~((u32v4)((((W[54]^(W[57]>>25))) & (1u<<4)) != 0) & (DV_II_50_0_bit|DV_II_52_0_bit));
	m[2] &= ~((u32v4)((((W[53]^(W[56]>>25))) & (1u<<4)) != 0) & (DV_II_49_0_bit|DV_II_51_0_bit));
	m[3] &= ~((u32v4)((((W[51]^(W[50]>>5))) & (1u<<1)) != 0) & (DV_I_50_2_bit|DV_II_46_2_bit));
	m[0] &= ~((u32v4)((((W[48]^W[50])) & (1u<<6)) != 0) & (DV_I_50_2_bit|DV_II_46_2_bit));
	m[1] &= ~((u32v4)((((W[48]^W[55])) & (uint32_t)536870912u) == 0) & (DV_I_51_0_bit|DV_I_52_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v4_part5(const u32v4 W[65], u32v4 m[4])
{
	m[2] &= ~((u32v4)((((W[47]^W[49])) & (1u<<6)) != 0) & (DV_I_49_2_bit|DV_I_51_2_bit));
	m[3] &= ~((u32v4)((((W[48]^(W[47]>>5))) & (1u<<1)) != 0) & (DV_I_47_2_bit|DV_II_51_2_bit));
	m[0] &= ~((u32v4)((((W[46]^W[48])) & (1u<<6)) != 0) & (DV_I_48_2_bit|DV_I_50_2_bit));
	m[1] &= ~((u32v4)((((W[47]^(W[46]>>5))) & (1u<<1)) != 0) & (DV_I_46_2_bit|DV_II_50_2_bit));
	m[2] &= ~((u32v4)((((W[44]^(W[45]>>5))) & (uint32_t)2u) == 0) & (DV_I_51_2_bit|DV_II_49_2_bit));
	m[3] &= ~((u32v4)((((W[43]^W[45])) & (1u<<6)) != 0) & (DV_I_47_2_bit|DV_I_49_2_bit));
	m[0] &= ~((u32v4)((((W[42]^W[44])) & (1u<<6)) != 0) & (DV_I_46_2_bit|DV_I_48_2_bit));
	m[1] &= ~((u32v4)((((W[43]^(W[42]>>5))) & (1u<<1)) != 0) & (DV_II_46_2_bit|DV_II_51_2_bit));
	m[2] &= ~((u32v4)((((W[42]^(W[41]>>5))) & (1u<<1)) != 0) & (DV_I_51_2_bit|DV_II_50_2_bit));
	m[3] &= ~((u32v4)((((W[41]^(W[40]>>5))) & (1u<<1)) != 0) & (DV_I_50_2_bit|DV_II_49_2_bit));
	m[0] &= ~((u32v4)((((W[39]^(W[43]>>25))) & (1u<<4)) != 0) & (DV_I_52_0_bit|DV_II_51_0_bit));
	m[1] &= ~((u32v4)((((W[38]^(W[42]>>25))) & (1u<<4)) != 0) & (DV_I_51_0_bit|DV_II_50_0_bit));
	m[2] &= ~((u32v4)((((W[37]^(W[38]>>5))) & (uint32_t)2u) == 0) & (DV_I_48_2_bit|DV_I_51_2_bit));
	m[3] &= ~((u32v4)((((W[37]^(W[41]>>25))) & (1u<<4)) != 0) & (DV_I_50_0_bit|DV_II_49_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v4_part6(const u32v4 W[65], u32v4 m[4])
{
	m[0] &= ~((u32v4)((((W[36]^W[38])) & (uint32_t)16u) == 0) & (DV_II_52_0_bit|DV_II_54_0_bit));
	m[1] &= ~((u32v4)((((W[35]^(W[36]>>5))) & (uint32_t)2u) == 0) & (DV_I_46_2_bit|DV_I_49_2_bit));
	m[2] &= ~((u32v4)((((W[35]^(W[39]>>25))) & (1u<<3)) != 0) & (DV_I_51_0_bit|DV_II_47_0_bit));
	{
		u32v4 keep = ((u32v4)((((W[61]^(W[62]>>5))) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[59]^(W[63]>>25))) & (1u<<5)) == 0));
		keep &= ((u32v4)((((W[58]^(W[63]>>30))) & (1u<<0)) != 0));
		m[3] &= keep | ~DV_I_43_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[62]^(W[63]>>5))) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[60]^(W[64]>>25))) & (1u<<5)) == 0));
		keep &= ((u32v4)((((W[59]^(W[64]>>30))) & (1u<<0)) != 0));
		m[0] &= keep | ~DV_I_44_0_bit;
	}
	m[1] &= ((~((W[40]^W[42])>>2)) | ~DV_I_46_2_bit);
	{
		u32v4 keep = ((u32v4)((((W[62]^(W[63]>>5))) & (1u<<2)) != 0));
		keep &= ((u32v4)((((W[41]^W[43])) & (1u<<6)) == 0));
		m[2] &= keep | ~DV_I_47_2_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[63]^(W[64]>>5))) & (1u<<2)) != 0));
		keep &= ((u32v4)((((W[48]^(W[49]<<5))) & (1u<<6)) == 0));
		m[3] &= keep | ~DV_I_48_2_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[49]^(W[50]<<5))) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[42]^W[50])) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[39]^(W[40]<<5))) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[38]^W[40])) & (1u<<1)) != 0));
		m[0] &= keep | ~DV_I_49_2_bit;
	}
	m[1] &= ((((W[36]^W[37])<<7)) | ~DV_I_50_0_bit);
	m[2] &= ((((W[43]^W[51])<<11)) | ~DV_I_50_2_bit);
	m[3] &= ((((W[37]^W[38])<<9)) | ~DV_I_51_0_bit);
	{
		u32v4 keep = ((u32v4)((((W[51]^(W[52]<<5))) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[49]^W[51])) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[37]^(W[37]>>5))) & (1u<<1)) == 0));
		keep &= ((u32v4)((((W[35]^(W[39]>>25))) & (1u<<5)) == 0));
		m[0] &= keep | ~DV_I_51_2_bit;
	}
	m[1] &= ((((W[38]^W[39])<<11)) | ~DV_I_52_0_bit);
}

SHA1DC_UBC_INLINE void ubc_check_v4_part7(const u32v4 W[65], u32v4 m[4])
{
	m[2] &= ((((W[47]^W[51])<<17)) | ~DV_II_46_2_bit);
	{
		u32v4 keep = ((u32v4)((((W[36]^(W[40]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[35]^(W[40]<<2))) & (1u<<30)) != 0));
		m[3] &= keep | ~DV_II_48_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[37]^(W[41]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[36]^(W[41]<<2))) & (1u<<30)) != 0));
		m[0] &= keep | ~DV_II_49_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[53]^(W[54]<<5))) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[51]^W[53])) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[50]^W[54])) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[45]^(W[46]<<5))) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[37]^(W[41]>>25))) & (1u<<5)) == 0));
		keep &= ((u32v4)((((W[36]^(W[41]>>30))) & (1u<<0)) != 0));
		m[1] &= keep | ~DV_II_49_2_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[55]^W[58])) & (1u<<29)) != 0));
		keep &= ((u32v4)((((W[38]^(W[42]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[37]^(W[42]<<2))) & (1u<<30)) != 0));
		m[2] &= keep | ~DV_II_50_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[54]^(W[55]<<5))) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[52]^W[54])) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[51]^W[55])) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[45]^W[47])) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[38]^(W[42]>>25))) & (1u<<5)) == 0));
		keep &= ((u32v4)((((W[37]^(W[42]>>30))) & (1u<<0)) != 0));
		m[3] &= keep | ~DV_II_50_2_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[39]^(W[43]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[38]^(W[43]<<2))) & (1u<<30)) != 0));
		m[0] &= keep | ~DV_II_51_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[55]^(W[56]<<5))) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[53]^W[55])) & (1u<<6)) == 0));
		keep &= ((u32v4)((((W[52]^W[56])) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[46]^W[48])) & (1u<<1)) != 0));
		keep &= ((u32v4)((((W[39]^(W[43]>>25))) & (1u<<5)) == 0));
		keep &= ((u32v4)((((W[38]^(W[43]>>30))) & (1u<<0)) != 0));
		m[1] &= keep | ~DV_II_51_2_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[59]^W[60])) & (1u<<29)) == 0));
		keep &= ((u32v4)((((W[40]^(W[44]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[40]^(W[44]>>25))) & (1u<<4)) == 0));
		keep &= ((u32v4)((((W[39]^(W[44]<<2))) & (1u<<30)) != 0));
		m[2] &= keep | ~DV_II_52_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[58]^W[61])) & (1u<<29)) != 0));
		keep &= ((u32v4)((((W[57]^(W[61]>>25))) & (1u<<4)) == 0));
		keep &= ((u32v4)((((W[41]^(W[45]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[41]^(W[45]>>25))) & (1u<<4)) == 0));
		m[3] &= keep | ~DV_II_53_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[58]^(W[62]>>25))) & (1u<<4)) == 0));
		keep &= ((u32v4)((((W[42]^(W[46]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[42]^(W[46]>>25))) & (1u<<4)) == 0));
		m[0] &= keep | ~DV_II_54_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[59]^(W[63]>>25))) & (1u<<4)) == 0));
		keep &= ((u32v4)((((W[57]^(W[59]>>25))) & (1u<<4)) == 0));
		keep &= ((u32v4)((((W[43]^(W[47]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[43]^(W[47]>>25))) & (1u<<4)) == 0));
		m[1] &= keep | ~DV_II_55_0_bit;
	}
	{
		u32v4 keep = ((u32v4)((((W[60]^(W[64]>>25))) & (1u<<4)) == 0));
		keep &= ((u32v4)((((W[44]^(W[48]>>25))) & (1u<<3)) == 0));
		keep &= ((u32v4)((((W[44]^(W[48]>>25))) & (1u<<4)) == 0));
		m[2] &= keep | ~DV_II_56_0_bit;
	}
}

#define UBC_V4_NPARTS 8
#define UBC_V4_EARLYOUT_AFTER_PART 7

SHA1DC_UBC_INLINE void ubc_check_v4_inline(const u32v4 W[65], u32v4 dvmask[1])
{
	u32v4 m[4] = { ~(u32v4){0}, ~(u32v4){0}, ~(u32v4){0}, ~(u32v4){0} };

	ubc_check_v4_part0(W, m);
	ubc_check_v4_part1(W, m);
	ubc_check_v4_part2(W, m);
	ubc_check_v4_part3(W, m);
	ubc_check_v4_part4(W, m);
	ubc_check_v4_part5(W, m);
	ubc_check_v4_part6(W, m);
	m[0] &= m[1] & m[2] & m[3];
	m[1] = m[2] = m[3] = ~(u32v4){0};
	if (ubc_v4_all_zero(&m[0])) { dvmask[0] = m[0]; return; }
	ubc_check_v4_part7(W, m);
	dvmask[0] = m[0] & m[1] & m[2] & m[3];
}
#endif /* UBC_CHECK_V4_H */
/* Generated by gen_ubc_simd.py from ubc_check.c (8 lanes). Do not edit. */
#ifndef UBC_CHECK_V8_H
#define UBC_CHECK_V8_H
#include <stdint.h>

typedef uint32_t u32v8 __attribute__((vector_size(32)));

static inline __attribute__((always_inline)) int ubc_v8_all_zero(const u32v8 *v)
{
	uint32_t a = 0;
	int i;
	for (i = 0; i < 8; i++)
		a |= (*v)[i];
	return a == 0;
}

#ifndef SHA1DC_UBC_DV_BITS
#define SHA1DC_UBC_DV_BITS
static const uint32_t DV_I_43_0_bit 	= (uint32_t)(1) << 0;
static const uint32_t DV_I_44_0_bit 	= (uint32_t)(1) << 1;
static const uint32_t DV_I_45_0_bit 	= (uint32_t)(1) << 2;
static const uint32_t DV_I_46_0_bit 	= (uint32_t)(1) << 3;
static const uint32_t DV_I_46_2_bit 	= (uint32_t)(1) << 4;
static const uint32_t DV_I_47_0_bit 	= (uint32_t)(1) << 5;
static const uint32_t DV_I_47_2_bit 	= (uint32_t)(1) << 6;
static const uint32_t DV_I_48_0_bit 	= (uint32_t)(1) << 7;
static const uint32_t DV_I_48_2_bit 	= (uint32_t)(1) << 8;
static const uint32_t DV_I_49_0_bit 	= (uint32_t)(1) << 9;
static const uint32_t DV_I_49_2_bit 	= (uint32_t)(1) << 10;
static const uint32_t DV_I_50_0_bit 	= (uint32_t)(1) << 11;
static const uint32_t DV_I_50_2_bit 	= (uint32_t)(1) << 12;
static const uint32_t DV_I_51_0_bit 	= (uint32_t)(1) << 13;
static const uint32_t DV_I_51_2_bit 	= (uint32_t)(1) << 14;
static const uint32_t DV_I_52_0_bit 	= (uint32_t)(1) << 15;
static const uint32_t DV_II_45_0_bit 	= (uint32_t)(1) << 16;
static const uint32_t DV_II_46_0_bit 	= (uint32_t)(1) << 17;
static const uint32_t DV_II_46_2_bit 	= (uint32_t)(1) << 18;
static const uint32_t DV_II_47_0_bit 	= (uint32_t)(1) << 19;
static const uint32_t DV_II_48_0_bit 	= (uint32_t)(1) << 20;
static const uint32_t DV_II_49_0_bit 	= (uint32_t)(1) << 21;
static const uint32_t DV_II_49_2_bit 	= (uint32_t)(1) << 22;
static const uint32_t DV_II_50_0_bit 	= (uint32_t)(1) << 23;
static const uint32_t DV_II_50_2_bit 	= (uint32_t)(1) << 24;
static const uint32_t DV_II_51_0_bit 	= (uint32_t)(1) << 25;
static const uint32_t DV_II_51_2_bit 	= (uint32_t)(1) << 26;
static const uint32_t DV_II_52_0_bit 	= (uint32_t)(1) << 27;
static const uint32_t DV_II_53_0_bit 	= (uint32_t)(1) << 28;
static const uint32_t DV_II_54_0_bit 	= (uint32_t)(1) << 29;
static const uint32_t DV_II_55_0_bit 	= (uint32_t)(1) << 30;
static const uint32_t DV_II_56_0_bit 	= (uint32_t)(1) << 31;
#endif /* SHA1DC_UBC_DV_BITS */

#ifndef SHA1DC_UBC_INLINE
#define SHA1DC_UBC_INLINE static inline __attribute__((always_inline))
#endif

SHA1DC_UBC_INLINE void ubc_check_v8_part0(const u32v8 W[65], u32v8 m[4])
{
	m[0] &= (((((W[44]^W[45])>>29)&1)-1) | ~(DV_I_48_0_bit|DV_I_51_0_bit|DV_I_52_0_bit|DV_II_45_0_bit|DV_II_46_0_bit|DV_II_50_0_bit|DV_II_51_0_bit));
	m[1] &= (((((W[49]^W[50])>>29)&1)-1) | ~(DV_I_46_0_bit|DV_II_45_0_bit|DV_II_50_0_bit|DV_II_51_0_bit|DV_II_55_0_bit|DV_II_56_0_bit));
	m[2] &= (((((W[48]^W[49])>>29)&1)-1) | ~(DV_I_45_0_bit|DV_I_52_0_bit|DV_II_49_0_bit|DV_II_50_0_bit|DV_II_54_0_bit|DV_II_55_0_bit));
	m[3] &= ((((W[47]^(W[50]>>25))&(1<<4))-(1<<4)) | ~(DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_51_0_bit|DV_II_56_0_bit));
	m[0] &= (((((W[47]^W[48])>>29)&1)-1) | ~(DV_I_44_0_bit|DV_I_51_0_bit|DV_II_48_0_bit|DV_II_49_0_bit|DV_II_53_0_bit|DV_II_54_0_bit));
	m[1] &= (((((W[46]>>4)^(W[49]>>29))&1)-1) | ~(DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit|DV_II_50_0_bit|DV_II_55_0_bit));
	m[2] &= (((((W[46]^W[47])>>29)&1)-1) | ~(DV_I_43_0_bit|DV_I_50_0_bit|DV_II_47_0_bit|DV_II_48_0_bit|DV_II_52_0_bit|DV_II_53_0_bit));
	m[3] &= (((((W[45]>>4)^(W[48]>>29))&1)-1) | ~(DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit|DV_II_49_0_bit|DV_II_54_0_bit));
	m[0] &= (((((W[45]^W[46])>>29)&1)-1) | ~(DV_I_49_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_47_0_bit|DV_II_51_0_bit|DV_II_52_0_bit));
	m[1] &= (((((W[44]>>4)^(W[47]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit|DV_II_48_0_bit|DV_II_53_0_bit));
	m[2] &= (((((W[43]>>4)^(W[46]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit|DV_II_47_0_bit|DV_II_52_0_bit));
	m[3] &= (((((W[43]^W[44])>>29)&1)-1) | ~(DV_I_47_0_bit|DV_I_50_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_49_0_bit|DV_II_50_0_bit));
	m[0] &= (((((W[42]>>4)^(W[45]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_51_0_bit));
	m[1] &= (((((W[41]>>4)^(W[44]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_50_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v8_part1(const u32v8 W[65], u32v8 m[4])
{
	m[2] &= (((((W[40]^W[41])>>29)&1)-1) | ~(DV_I_44_0_bit|DV_I_47_0_bit|DV_I_48_0_bit|DV_II_46_0_bit|DV_II_47_0_bit|DV_II_56_0_bit));
	m[3] &= (((((W[54]^W[55])>>29)&1)-1) | ~(DV_I_51_0_bit|DV_II_47_0_bit|DV_II_50_0_bit|DV_II_55_0_bit|DV_II_56_0_bit));
	m[0] &= (((((W[53]^W[54])>>29)&1)-1) | ~(DV_I_50_0_bit|DV_II_46_0_bit|DV_II_49_0_bit|DV_II_54_0_bit|DV_II_55_0_bit));
	m[1] &= (((((W[52]^W[53])>>29)&1)-1) | ~(DV_I_49_0_bit|DV_II_45_0_bit|DV_II_48_0_bit|DV_II_53_0_bit|DV_II_54_0_bit));
	m[2] &= ((((W[50]^(W[53]>>25))&(1<<4))-(1<<4)) | ~(DV_I_50_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_48_0_bit|DV_II_54_0_bit));
	m[3] &= (((((W[50]^W[51])>>29)&1)-1) | ~(DV_I_47_0_bit|DV_II_46_0_bit|DV_II_51_0_bit|DV_II_52_0_bit|DV_II_56_0_bit));
	m[0] &= ((((W[49]^(W[52]>>25))&(1<<4))-(1<<4)) | ~(DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_47_0_bit|DV_II_53_0_bit));
	m[1] &= ((((W[48]^(W[51]>>25))&(1<<4))-(1<<4)) | ~(DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_52_0_bit));
	m[2] &= (((((W[42]^W[43])>>29)&1)-1) | ~(DV_I_46_0_bit|DV_I_49_0_bit|DV_I_50_0_bit|DV_II_48_0_bit|DV_II_49_0_bit));
	m[3] &= (((((W[41]^W[42])>>29)&1)-1) | ~(DV_I_45_0_bit|DV_I_48_0_bit|DV_I_49_0_bit|DV_II_47_0_bit|DV_II_48_0_bit));
	m[0] &= (((((W[40]>>4)^(W[43]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_50_0_bit|DV_II_49_0_bit|DV_II_56_0_bit));
	m[1] &= (((((W[39]>>4)^(W[42]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_49_0_bit|DV_II_48_0_bit|DV_II_55_0_bit));
	m[2] &= (((((W[38]>>4)^(W[41]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_48_0_bit|DV_II_47_0_bit|DV_II_54_0_bit|DV_II_56_0_bit));
	m[3] &= (((((W[37]>>4)^(W[40]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_47_0_bit|DV_II_46_0_bit|DV_II_53_0_bit|DV_II_55_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v8_part2(const u32v8 W[65], u32v8 m[4])
{
	m[0] &= (((((W[55]^W[56])>>29)&1)-1) | ~(DV_I_52_0_bit|DV_II_48_0_bit|DV_II_51_0_bit|DV_II_56_0_bit));
	m[1] &= ((((W[52]^(W[55]>>25))&(1<<4))-(1<<4)) | ~(DV_I_52_0_bit|DV_II_48_0_bit|DV_II_50_0_bit|DV_II_56_0_bit));
	m[2] &= ((((W[51]^(W[54]>>25))&(1<<4))-(1<<4)) | ~(DV_I_51_0_bit|DV_II_47_0_bit|DV_II_49_0_bit|DV_II_55_0_bit));
	m[3] &= (((((W[51]^W[52])>>29)&1)-1) | ~(DV_I_48_0_bit|DV_II_47_0_bit|DV_II_52_0_bit|DV_II_53_0_bit));
	m[0] &= (((((W[36]>>4)^(W[40]>>29))&1)-1) | ~(DV_I_46_0_bit|DV_I_49_0_bit|DV_II_45_0_bit|DV_II_48_0_bit));
	m[1] &= ((0-(((W[53]^W[56])>>29)&1)) | ~(DV_I_52_0_bit|DV_II_48_0_bit|DV_II_49_0_bit));
	m[2] &= ((0-(((W[51]^W[54])>>29)&1)) | ~(DV_I_50_0_bit|DV_II_46_0_bit|DV_II_47_0_bit));
	m[3] &= ((0-(((W[50]^W[52])>>29)&1)) | ~(DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit));
	m[0] &= ((0-(((W[49]^W[51])>>29)&1)) | ~(DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit));
	m[1] &= ((0-(((W[48]^W[50])>>29)&1)) | ~(DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit));
	m[2] &= ((0-(((W[47]^W[49])>>29)&1)) | ~(DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit));
	m[3] &= ((0-(((W[46]^W[48])>>29)&1)) | ~(DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit));
	m[0] &= ((((W[45]^W[47])&(1<<6))-(1<<6)) | ~(DV_I_47_2_bit|DV_I_49_2_bit|DV_I_51_2_bit));
	m[1] &= ((0-(((W[45]^W[47])>>29)&1)) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v8_part3(const u32v8 W[65], u32v8 m[4])
{
	m[2] &= (((((W[44]^W[46])>>6)&1)-1) | ~(DV_I_46_2_bit|DV_I_48_2_bit|DV_I_50_2_bit));
	m[3] &= ((0-(((W[44]^W[46])>>29)&1)) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit));
	m[0] &= ((0-((W[41]^(W[42]>>5))&(1<<1))) | ~(DV_I_48_2_bit|DV_II_46_2_bit|DV_II_51_2_bit));
	m[1] &= ((0-((W[40]^(W[41]>>5))&(1<<1))) | ~(DV_I_47_2_bit|DV_I_51_2_bit|DV_II_50_2_bit));
	m[2] &= ((0-(((W[40]^W[42])>>4)&1)) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_II_56_0_bit));
	m[3] &= ((0-((W[39]^(W[40]>>5))&(1<<1))) | ~(DV_I_46_2_bit|DV_I_50_2_bit|DV_II_49_2_bit));
	m[0] &= ((0-(((W[39]^W[41])>>4)&1)) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_II_55_0_bit));
	m[1] &= ((0-(((W[38]^W[40])>>4)&1)) | ~(DV_I_44_0_bit|DV_II_54_0_bit|DV_II_56_0_bit));
	m[2] &= ((0-(((W[37]^W[39])>>4)&1)) | ~(DV_I_43_0_bit|DV_II_53_0_bit|DV_II_55_0_bit));
	m[3] &= ((0-((W[36]^(W[37]>>5))&(1<<1))) | ~(DV_I_47_2_bit|DV_I_50_2_bit|DV_II_46_2_bit));
	m[0] &= (((((W[35]>>4)^(W[39]>>29))&1)-1) | ~(DV_I_45_0_bit|DV_I_48_0_bit|DV_II_47_0_bit));
	m[1] &= ((0-((W[63]^(W[64]>>5))&(1<<0))) | ~(DV_I_48_0_bit|DV_II_48_0_bit));
	m[2] &= ((0-((W[63]^(W[64]>>5))&(1<<1))) | ~(DV_I_45_0_bit|DV_II_45_0_bit));
	m[3] &= ((0-((W[62]^(W[63]>>5))&(1<<0))) | ~(DV_I_47_0_bit|DV_II_47_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v8_part4(const u32v8 W[65], u32v8 m[4])
{
	m[0] &= ((0-((W[61]^(W[62]>>5))&(1<<0))) | ~(DV_I_46_0_bit|DV_II_46_0_bit));
	m[1] &= ((0-((W[61]^(W[62]>>5))&(1<<2))) | ~(DV_I_46_2_bit|DV_II_46_2_bit));
	m[2] &= ((0-((W[60]^(W[61]>>5))&(1<<0))) | ~(DV_I_45_0_bit|DV_II_45_0_bit));
	m[3] &= (((((W[58]^W[59])>>29)&1)-1) | ~(DV_II_51_0_bit|DV_II_54_0_bit));
	m[0] &= (((((W[57]^W[58])>>29)&1)-1) | ~(DV_II_50_0_bit|DV_II_53_0_bit));
	m[1] &= ((((W[56]^(W[59]>>25))&(1<<4))-(1<<4)) | ~(DV_II_52_0_bit|DV_II_54_0_bit));
	m[2] &= ((0-(((W[56]^W[59])>>29)&1)) | ~(DV_II_51_0_bit|DV_II_52_0_bit));
	m[3] &= (((((W[56]^W[57])>>29)&1)-1) | ~(DV_II_49_0_bit|DV_II_52_0_bit));
	m[0] &= ((((W[55]^(W[58]>>25))&(1<<4))-(1<<4)) | ~(DV_II_51_0_bit|DV_II_53_0_bit));
	m[1] &= ((((W[54]^(W[57]>>25))&(1<<4))-(1<<4)) | ~(DV_II_50_0_bit|DV_II_52_0_bit));
	m[2] &= ((((W[53]^(W[56]>>25))&(1<<4))-(1<<4)) | ~(DV_II_49_0_bit|DV_II_51_0_bit));
	m[3] &= ((((W[51]^(W[50]>>5))&(1<<1))-(1<<1)) | ~(DV_I_50_2_bit|DV_II_46_2_bit));
	m[0] &= ((((W[48]^W[50])&(1<<6))-(1<<6)) | ~(DV_I_50_2_bit|DV_II_46_2_bit));
	m[1] &= ((0-(((W[48]^W[55])>>29)&1)) | ~(DV_I_51_0_bit|DV_I_52_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v8_part5(const u32v8 W[65], u32v8 m[4])
{
	m[2] &= ((((W[47]^W[49])&(1<<6))-(1<<6)) | ~(DV_I_49_2_bit|DV_I_51_2_bit));
	m[3] &= ((((W[48]^(W[47]>>5))&(1<<1))-(1<<1)) | ~(DV_I_47_2_bit|DV_II_51_2_bit));
	m[0] &= ((((W[46]^W[48])&(1<<6))-(1<<6)) | ~(DV_I_48_2_bit|DV_I_50_2_bit));
	m[1] &= ((((W[47]^(W[46]>>5))&(1<<1))-(1<<1)) | ~(DV_I_46_2_bit|DV_II_50_2_bit));
	m[2] &= ((0-((W[44]^(W[45]>>5))&(1<<1))) | ~(DV_I_51_2_bit|DV_II_49_2_bit));
	m[3] &= ((((W[43]^W[45])&(1<<6))-(1<<6)) | ~(DV_I_47_2_bit|DV_I_49_2_bit));
	m[0] &= (((((W[42]^W[44])>>6)&1)-1) | ~(DV_I_46_2_bit|DV_I_48_2_bit));
	m[1] &= ((((W[43]^(W[42]>>5))&(1<<1))-(1<<1)) | ~(DV_II_46_2_bit|DV_II_51_2_bit));
	m[2] &= ((((W[42]^(W[41]>>5))&(1<<1))-(1<<1)) | ~(DV_I_51_2_bit|DV_II_50_2_bit));
	m[3] &= ((((W[41]^(W[40]>>5))&(1<<1))-(1<<1)) | ~(DV_I_50_2_bit|DV_II_49_2_bit));
	m[0] &= ((((W[39]^(W[43]>>25))&(1<<4))-(1<<4)) | ~(DV_I_52_0_bit|DV_II_51_0_bit));
	m[1] &= ((((W[38]^(W[42]>>25))&(1<<4))-(1<<4)) | ~(DV_I_51_0_bit|DV_II_50_0_bit));
	m[2] &= ((0-((W[37]^(W[38]>>5))&(1<<1))) | ~(DV_I_48_2_bit|DV_I_51_2_bit));
	m[3] &= ((((W[37]^(W[41]>>25))&(1<<4))-(1<<4)) | ~(DV_I_50_0_bit|DV_II_49_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v8_part6(const u32v8 W[65], u32v8 m[4])
{
	m[0] &= ((0-((W[36]^W[38])&(1<<4))) | ~(DV_II_52_0_bit|DV_II_54_0_bit));
	m[1] &= ((0-((W[35]^(W[36]>>5))&(1<<1))) | ~(DV_I_46_2_bit|DV_I_49_2_bit));
	m[2] &= ((((W[35]^(W[39]>>25))&(1<<3))-(1<<3)) | ~(DV_I_51_0_bit|DV_II_47_0_bit));
	{
		u32v8 keep = ((((W[61]^(W[62]>>5))) >> 1) & 1);
		keep &= (((((W[59]^(W[63]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[58]^(W[63]>>30))) >> 0) & 1);
		m[3] &= -keep | ~DV_I_43_0_bit;
	}
	{
		u32v8 keep = ((((W[62]^(W[63]>>5))) >> 1) & 1);
		keep &= (((((W[60]^(W[64]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[59]^(W[64]>>30))) >> 0) & 1);
		m[0] &= -keep | ~DV_I_44_0_bit;
	}
	m[1] &= ((~((W[40]^W[42])>>2)) | ~DV_I_46_2_bit);
	{
		u32v8 keep = ((((W[62]^(W[63]>>5))) >> 2) & 1);
		keep &= (((((W[41]^W[43])) >> 6) & 1) ^ 1);
		m[2] &= -keep | ~DV_I_47_2_bit;
	}
	{
		u32v8 keep = ((((W[63]^(W[64]>>5))) >> 2) & 1);
		keep &= (((((W[48]^(W[49]<<5))) >> 6) & 1) ^ 1);
		m[3] &= -keep | ~DV_I_48_2_bit;
	}
	{
		u32v8 keep = (((((W[49]^(W[50]<<5))) >> 6) & 1) ^ 1);
		keep &= ((((W[42]^W[50])) >> 1) & 1);
		keep &= (((((W[39]^(W[40]<<5))) >> 6) & 1) ^ 1);
		keep &= ((((W[38]^W[40])) >> 1) & 1);
		m[0] &= -keep | ~DV_I_49_2_bit;
	}
	m[1] &= ((((W[36]^W[37])<<7)) | ~DV_I_50_0_bit);
	m[2] &= ((((W[43]^W[51])<<11)) | ~DV_I_50_2_bit);
	m[3] &= ((((W[37]^W[38])<<9)) | ~DV_I_51_0_bit);
	{
		u32v8 keep = (((((W[51]^(W[52]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[49]^W[51])) >> 6) & 1) ^ 1);
		keep &= (((((W[37]^(W[37]>>5))) >> 1) & 1) ^ 1);
		keep &= (((((W[35]^(W[39]>>25))) >> 5) & 1) ^ 1);
		m[0] &= -keep | ~DV_I_51_2_bit;
	}
	m[1] &= ((((W[38]^W[39])<<11)) | ~DV_I_52_0_bit);
}

SHA1DC_UBC_INLINE void ubc_check_v8_part7(const u32v8 W[65], u32v8 m[4])
{
	m[2] &= ((((W[47]^W[51])<<17)) | ~DV_II_46_2_bit);
	{
		u32v8 keep = (((((W[36]^(W[40]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[35]^(W[40]<<2))) >> 30) & 1);
		m[3] &= -keep | ~DV_II_48_0_bit;
	}
	{
		u32v8 keep = (((((W[37]^(W[41]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[36]^(W[41]<<2))) >> 30) & 1);
		m[0] &= -keep | ~DV_II_49_0_bit;
	}
	{
		u32v8 keep = (((((W[53]^(W[54]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[51]^W[53])) >> 6) & 1) ^ 1);
		keep &= ((((W[50]^W[54])) >> 1) & 1);
		keep &= (((((W[45]^(W[46]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[37]^(W[41]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[36]^(W[41]>>30))) >> 0) & 1);
		m[1] &= -keep | ~DV_II_49_2_bit;
	}
	{
		u32v8 keep = ((((W[55]^W[58])) >> 29) & 1);
		keep &= (((((W[38]^(W[42]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[37]^(W[42]<<2))) >> 30) & 1);
		m[2] &= -keep | ~DV_II_50_0_bit;
	}
	{
		u32v8 keep = (((((W[54]^(W[55]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[52]^W[54])) >> 6) & 1) ^ 1);
		keep &= ((((W[51]^W[55])) >> 1) & 1);
		keep &= ((((W[45]^W[47])) >> 1) & 1);
		keep &= (((((W[38]^(W[42]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[37]^(W[42]>>30))) >> 0) & 1);
		m[3] &= -keep | ~DV_II_50_2_bit;
	}
	{
		u32v8 keep = (((((W[39]^(W[43]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[38]^(W[43]<<2))) >> 30) & 1);
		m[0] &= -keep | ~DV_II_51_0_bit;
	}
	{
		u32v8 keep = (((((W[55]^(W[56]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[53]^W[55])) >> 6) & 1) ^ 1);
		keep &= ((((W[52]^W[56])) >> 1) & 1);
		keep &= ((((W[46]^W[48])) >> 1) & 1);
		keep &= (((((W[39]^(W[43]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[38]^(W[43]>>30))) >> 0) & 1);
		m[1] &= -keep | ~DV_II_51_2_bit;
	}
	{
		u32v8 keep = (((((W[59]^W[60])) >> 29) & 1) ^ 1);
		keep &= (((((W[40]^(W[44]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[40]^(W[44]>>25))) >> 4) & 1) ^ 1);
		keep &= ((((W[39]^(W[44]<<2))) >> 30) & 1);
		m[2] &= -keep | ~DV_II_52_0_bit;
	}
	{
		u32v8 keep = ((((W[58]^W[61])) >> 29) & 1);
		keep &= (((((W[57]^(W[61]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[41]^(W[45]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[41]^(W[45]>>25))) >> 4) & 1) ^ 1);
		m[3] &= -keep | ~DV_II_53_0_bit;
	}
	{
		u32v8 keep = (((((W[58]^(W[62]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[42]^(W[46]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[42]^(W[46]>>25))) >> 4) & 1) ^ 1);
		m[0] &= -keep | ~DV_II_54_0_bit;
	}
	{
		u32v8 keep = (((((W[59]^(W[63]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[57]^(W[59]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[43]^(W[47]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[43]^(W[47]>>25))) >> 4) & 1) ^ 1);
		m[1] &= -keep | ~DV_II_55_0_bit;
	}
	{
		u32v8 keep = (((((W[60]^(W[64]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[44]^(W[48]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[44]^(W[48]>>25))) >> 4) & 1) ^ 1);
		m[2] &= -keep | ~DV_II_56_0_bit;
	}
}

#define UBC_V8_NPARTS 8
#define UBC_V8_EARLYOUT_AFTER_PART 7

SHA1DC_UBC_INLINE void ubc_check_v8_inline(const u32v8 W[65], u32v8 dvmask[1])
{
	u32v8 m[4] = { ~(u32v8){0}, ~(u32v8){0}, ~(u32v8){0}, ~(u32v8){0} };

	ubc_check_v8_part0(W, m);
	ubc_check_v8_part1(W, m);
	ubc_check_v8_part2(W, m);
	ubc_check_v8_part3(W, m);
	ubc_check_v8_part4(W, m);
	ubc_check_v8_part5(W, m);
	ubc_check_v8_part6(W, m);
	m[0] &= m[1] & m[2] & m[3];
	m[1] = m[2] = m[3] = ~(u32v8){0};
	if (ubc_v8_all_zero(&m[0])) { dvmask[0] = m[0]; return; }
	ubc_check_v8_part7(W, m);
	dvmask[0] = m[0] & m[1] & m[2] & m[3];
}
#endif /* UBC_CHECK_V8_H */
/* Generated by gen_ubc_simd.py from ubc_check.c (16 lanes). Do not edit. */
#ifndef UBC_CHECK_V16_H
#define UBC_CHECK_V16_H
#include <stdint.h>

typedef uint32_t u32v16 __attribute__((vector_size(64)));

static inline __attribute__((always_inline)) int ubc_v16_all_zero(const u32v16 *v)
{
	uint32_t a = 0;
	int i;
	for (i = 0; i < 16; i++)
		a |= (*v)[i];
	return a == 0;
}

#ifndef SHA1DC_UBC_DV_BITS
#define SHA1DC_UBC_DV_BITS
static const uint32_t DV_I_43_0_bit 	= (uint32_t)(1) << 0;
static const uint32_t DV_I_44_0_bit 	= (uint32_t)(1) << 1;
static const uint32_t DV_I_45_0_bit 	= (uint32_t)(1) << 2;
static const uint32_t DV_I_46_0_bit 	= (uint32_t)(1) << 3;
static const uint32_t DV_I_46_2_bit 	= (uint32_t)(1) << 4;
static const uint32_t DV_I_47_0_bit 	= (uint32_t)(1) << 5;
static const uint32_t DV_I_47_2_bit 	= (uint32_t)(1) << 6;
static const uint32_t DV_I_48_0_bit 	= (uint32_t)(1) << 7;
static const uint32_t DV_I_48_2_bit 	= (uint32_t)(1) << 8;
static const uint32_t DV_I_49_0_bit 	= (uint32_t)(1) << 9;
static const uint32_t DV_I_49_2_bit 	= (uint32_t)(1) << 10;
static const uint32_t DV_I_50_0_bit 	= (uint32_t)(1) << 11;
static const uint32_t DV_I_50_2_bit 	= (uint32_t)(1) << 12;
static const uint32_t DV_I_51_0_bit 	= (uint32_t)(1) << 13;
static const uint32_t DV_I_51_2_bit 	= (uint32_t)(1) << 14;
static const uint32_t DV_I_52_0_bit 	= (uint32_t)(1) << 15;
static const uint32_t DV_II_45_0_bit 	= (uint32_t)(1) << 16;
static const uint32_t DV_II_46_0_bit 	= (uint32_t)(1) << 17;
static const uint32_t DV_II_46_2_bit 	= (uint32_t)(1) << 18;
static const uint32_t DV_II_47_0_bit 	= (uint32_t)(1) << 19;
static const uint32_t DV_II_48_0_bit 	= (uint32_t)(1) << 20;
static const uint32_t DV_II_49_0_bit 	= (uint32_t)(1) << 21;
static const uint32_t DV_II_49_2_bit 	= (uint32_t)(1) << 22;
static const uint32_t DV_II_50_0_bit 	= (uint32_t)(1) << 23;
static const uint32_t DV_II_50_2_bit 	= (uint32_t)(1) << 24;
static const uint32_t DV_II_51_0_bit 	= (uint32_t)(1) << 25;
static const uint32_t DV_II_51_2_bit 	= (uint32_t)(1) << 26;
static const uint32_t DV_II_52_0_bit 	= (uint32_t)(1) << 27;
static const uint32_t DV_II_53_0_bit 	= (uint32_t)(1) << 28;
static const uint32_t DV_II_54_0_bit 	= (uint32_t)(1) << 29;
static const uint32_t DV_II_55_0_bit 	= (uint32_t)(1) << 30;
static const uint32_t DV_II_56_0_bit 	= (uint32_t)(1) << 31;
#endif /* SHA1DC_UBC_DV_BITS */

#ifndef SHA1DC_UBC_INLINE
#define SHA1DC_UBC_INLINE static inline __attribute__((always_inline))
#endif

SHA1DC_UBC_INLINE void ubc_check_v16_part0(const u32v16 W[65], u32v16 m[4])
{
	m[0] &= (((((W[44]^W[45])>>29)&1)-1) | ~(DV_I_48_0_bit|DV_I_51_0_bit|DV_I_52_0_bit|DV_II_45_0_bit|DV_II_46_0_bit|DV_II_50_0_bit|DV_II_51_0_bit));
	m[1] &= (((((W[49]^W[50])>>29)&1)-1) | ~(DV_I_46_0_bit|DV_II_45_0_bit|DV_II_50_0_bit|DV_II_51_0_bit|DV_II_55_0_bit|DV_II_56_0_bit));
	m[2] &= (((((W[48]^W[49])>>29)&1)-1) | ~(DV_I_45_0_bit|DV_I_52_0_bit|DV_II_49_0_bit|DV_II_50_0_bit|DV_II_54_0_bit|DV_II_55_0_bit));
	m[3] &= ((((W[47]^(W[50]>>25))&(1<<4))-(1<<4)) | ~(DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_51_0_bit|DV_II_56_0_bit));
	m[0] &= (((((W[47]^W[48])>>29)&1)-1) | ~(DV_I_44_0_bit|DV_I_51_0_bit|DV_II_48_0_bit|DV_II_49_0_bit|DV_II_53_0_bit|DV_II_54_0_bit));
	m[1] &= (((((W[46]>>4)^(W[49]>>29))&1)-1) | ~(DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit|DV_II_50_0_bit|DV_II_55_0_bit));
	m[2] &= (((((W[46]^W[47])>>29)&1)-1) | ~(DV_I_43_0_bit|DV_I_50_0_bit|DV_II_47_0_bit|DV_II_48_0_bit|DV_II_52_0_bit|DV_II_53_0_bit));
	m[3] &= (((((W[45]>>4)^(W[48]>>29))&1)-1) | ~(DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit|DV_II_49_0_bit|DV_II_54_0_bit));
	m[0] &= (((((W[45]^W[46])>>29)&1)-1) | ~(DV_I_49_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_47_0_bit|DV_II_51_0_bit|DV_II_52_0_bit));
	m[1] &= (((((W[44]>>4)^(W[47]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit|DV_II_48_0_bit|DV_II_53_0_bit));
	m[2] &= (((((W[43]>>4)^(W[46]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit|DV_II_47_0_bit|DV_II_52_0_bit));
	m[3] &= (((((W[43]^W[44])>>29)&1)-1) | ~(DV_I_47_0_bit|DV_I_50_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_49_0_bit|DV_II_50_0_bit));
	m[0] &= (((((W[42]>>4)^(W[45]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_51_0_bit));
	m[1] &= (((((W[41]>>4)^(W[44]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_50_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v16_part1(const u32v16 W[65], u32v16 m[4])
{
	m[2] &= (((((W[40]^W[41])>>29)&1)-1) | ~(DV_I_44_0_bit|DV_I_47_0_bit|DV_I_48_0_bit|DV_II_46_0_bit|DV_II_47_0_bit|DV_II_56_0_bit));
	m[3] &= (((((W[54]^W[55])>>29)&1)-1) | ~(DV_I_51_0_bit|DV_II_47_0_bit|DV_II_50_0_bit|DV_II_55_0_bit|DV_II_56_0_bit));
	m[0] &= (((((W[53]^W[54])>>29)&1)-1) | ~(DV_I_50_0_bit|DV_II_46_0_bit|DV_II_49_0_bit|DV_II_54_0_bit|DV_II_55_0_bit));
	m[1] &= (((((W[52]^W[53])>>29)&1)-1) | ~(DV_I_49_0_bit|DV_II_45_0_bit|DV_II_48_0_bit|DV_II_53_0_bit|DV_II_54_0_bit));
	m[2] &= ((((W[50]^(W[53]>>25))&(1<<4))-(1<<4)) | ~(DV_I_50_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_48_0_bit|DV_II_54_0_bit));
	m[3] &= (((((W[50]^W[51])>>29)&1)-1) | ~(DV_I_47_0_bit|DV_II_46_0_bit|DV_II_51_0_bit|DV_II_52_0_bit|DV_II_56_0_bit));
	m[0] &= ((((W[49]^(W[52]>>25))&(1<<4))-(1<<4)) | ~(DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit|DV_II_47_0_bit|DV_II_53_0_bit));
	m[1] &= ((((W[48]^(W[51]>>25))&(1<<4))-(1<<4)) | ~(DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit|DV_II_46_0_bit|DV_II_52_0_bit));
	m[2] &= (((((W[42]^W[43])>>29)&1)-1) | ~(DV_I_46_0_bit|DV_I_49_0_bit|DV_I_50_0_bit|DV_II_48_0_bit|DV_II_49_0_bit));
	m[3] &= (((((W[41]^W[42])>>29)&1)-1) | ~(DV_I_45_0_bit|DV_I_48_0_bit|DV_I_49_0_bit|DV_II_47_0_bit|DV_II_48_0_bit));
	m[0] &= (((((W[40]>>4)^(W[43]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_50_0_bit|DV_II_49_0_bit|DV_II_56_0_bit));
	m[1] &= (((((W[39]>>4)^(W[42]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_49_0_bit|DV_II_48_0_bit|DV_II_55_0_bit));
	m[2] &= (((((W[38]>>4)^(W[41]>>29))&1)-1) | ~(DV_I_44_0_bit|DV_I_48_0_bit|DV_II_47_0_bit|DV_II_54_0_bit|DV_II_56_0_bit));
	m[3] &= (((((W[37]>>4)^(W[40]>>29))&1)-1) | ~(DV_I_43_0_bit|DV_I_47_0_bit|DV_II_46_0_bit|DV_II_53_0_bit|DV_II_55_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v16_part2(const u32v16 W[65], u32v16 m[4])
{
	m[0] &= (((((W[55]^W[56])>>29)&1)-1) | ~(DV_I_52_0_bit|DV_II_48_0_bit|DV_II_51_0_bit|DV_II_56_0_bit));
	m[1] &= ((((W[52]^(W[55]>>25))&(1<<4))-(1<<4)) | ~(DV_I_52_0_bit|DV_II_48_0_bit|DV_II_50_0_bit|DV_II_56_0_bit));
	m[2] &= ((((W[51]^(W[54]>>25))&(1<<4))-(1<<4)) | ~(DV_I_51_0_bit|DV_II_47_0_bit|DV_II_49_0_bit|DV_II_55_0_bit));
	m[3] &= (((((W[51]^W[52])>>29)&1)-1) | ~(DV_I_48_0_bit|DV_II_47_0_bit|DV_II_52_0_bit|DV_II_53_0_bit));
	m[0] &= (((((W[36]>>4)^(W[40]>>29))&1)-1) | ~(DV_I_46_0_bit|DV_I_49_0_bit|DV_II_45_0_bit|DV_II_48_0_bit));
	m[1] &= ((0-(((W[53]^W[56])>>29)&1)) | ~(DV_I_52_0_bit|DV_II_48_0_bit|DV_II_49_0_bit));
	m[2] &= ((0-(((W[51]^W[54])>>29)&1)) | ~(DV_I_50_0_bit|DV_II_46_0_bit|DV_II_47_0_bit));
	m[3] &= ((0-(((W[50]^W[52])>>29)&1)) | ~(DV_I_49_0_bit|DV_I_51_0_bit|DV_II_45_0_bit));
	m[0] &= ((0-(((W[49]^W[51])>>29)&1)) | ~(DV_I_48_0_bit|DV_I_50_0_bit|DV_I_52_0_bit));
	m[1] &= ((0-(((W[48]^W[50])>>29)&1)) | ~(DV_I_47_0_bit|DV_I_49_0_bit|DV_I_51_0_bit));
	m[2] &= ((0-(((W[47]^W[49])>>29)&1)) | ~(DV_I_46_0_bit|DV_I_48_0_bit|DV_I_50_0_bit));
	m[3] &= ((0-(((W[46]^W[48])>>29)&1)) | ~(DV_I_45_0_bit|DV_I_47_0_bit|DV_I_49_0_bit));
	m[0] &= ((((W[45]^W[47])&(1<<6))-(1<<6)) | ~(DV_I_47_2_bit|DV_I_49_2_bit|DV_I_51_2_bit));
	m[1] &= ((0-(((W[45]^W[47])>>29)&1)) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_I_48_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v16_part3(const u32v16 W[65], u32v16 m[4])
{
	m[2] &= (((((W[44]^W[46])>>6)&1)-1) | ~(DV_I_46_2_bit|DV_I_48_2_bit|DV_I_50_2_bit));
	m[3] &= ((0-(((W[44]^W[46])>>29)&1)) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_I_47_0_bit));
	m[0] &= ((0-((W[41]^(W[42]>>5))&(1<<1))) | ~(DV_I_48_2_bit|DV_II_46_2_bit|DV_II_51_2_bit));
	m[1] &= ((0-((W[40]^(W[41]>>5))&(1<<1))) | ~(DV_I_47_2_bit|DV_I_51_2_bit|DV_II_50_2_bit));
	m[2] &= ((0-(((W[40]^W[42])>>4)&1)) | ~(DV_I_44_0_bit|DV_I_46_0_bit|DV_II_56_0_bit));
	m[3] &= ((0-((W[39]^(W[40]>>5))&(1<<1))) | ~(DV_I_46_2_bit|DV_I_50_2_bit|DV_II_49_2_bit));
	m[0] &= ((0-(((W[39]^W[41])>>4)&1)) | ~(DV_I_43_0_bit|DV_I_45_0_bit|DV_II_55_0_bit));
	m[1] &= ((0-(((W[38]^W[40])>>4)&1)) | ~(DV_I_44_0_bit|DV_II_54_0_bit|DV_II_56_0_bit));
	m[2] &= ((0-(((W[37]^W[39])>>4)&1)) | ~(DV_I_43_0_bit|DV_II_53_0_bit|DV_II_55_0_bit));
	m[3] &= ((0-((W[36]^(W[37]>>5))&(1<<1))) | ~(DV_I_47_2_bit|DV_I_50_2_bit|DV_II_46_2_bit));
	m[0] &= (((((W[35]>>4)^(W[39]>>29))&1)-1) | ~(DV_I_45_0_bit|DV_I_48_0_bit|DV_II_47_0_bit));
	m[1] &= ((0-((W[63]^(W[64]>>5))&(1<<0))) | ~(DV_I_48_0_bit|DV_II_48_0_bit));
	m[2] &= ((0-((W[63]^(W[64]>>5))&(1<<1))) | ~(DV_I_45_0_bit|DV_II_45_0_bit));
	m[3] &= ((0-((W[62]^(W[63]>>5))&(1<<0))) | ~(DV_I_47_0_bit|DV_II_47_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v16_part4(const u32v16 W[65], u32v16 m[4])
{
	m[0] &= ((0-((W[61]^(W[62]>>5))&(1<<0))) | ~(DV_I_46_0_bit|DV_II_46_0_bit));
	m[1] &= ((0-((W[61]^(W[62]>>5))&(1<<2))) | ~(DV_I_46_2_bit|DV_II_46_2_bit));
	m[2] &= ((0-((W[60]^(W[61]>>5))&(1<<0))) | ~(DV_I_45_0_bit|DV_II_45_0_bit));
	m[3] &= (((((W[58]^W[59])>>29)&1)-1) | ~(DV_II_51_0_bit|DV_II_54_0_bit));
	m[0] &= (((((W[57]^W[58])>>29)&1)-1) | ~(DV_II_50_0_bit|DV_II_53_0_bit));
	m[1] &= ((((W[56]^(W[59]>>25))&(1<<4))-(1<<4)) | ~(DV_II_52_0_bit|DV_II_54_0_bit));
	m[2] &= ((0-(((W[56]^W[59])>>29)&1)) | ~(DV_II_51_0_bit|DV_II_52_0_bit));
	m[3] &= (((((W[56]^W[57])>>29)&1)-1) | ~(DV_II_49_0_bit|DV_II_52_0_bit));
	m[0] &= ((((W[55]^(W[58]>>25))&(1<<4))-(1<<4)) | ~(DV_II_51_0_bit|DV_II_53_0_bit));
	m[1] &= ((((W[54]^(W[57]>>25))&(1<<4))-(1<<4)) | ~(DV_II_50_0_bit|DV_II_52_0_bit));
	m[2] &= ((((W[53]^(W[56]>>25))&(1<<4))-(1<<4)) | ~(DV_II_49_0_bit|DV_II_51_0_bit));
	m[3] &= ((((W[51]^(W[50]>>5))&(1<<1))-(1<<1)) | ~(DV_I_50_2_bit|DV_II_46_2_bit));
	m[0] &= ((((W[48]^W[50])&(1<<6))-(1<<6)) | ~(DV_I_50_2_bit|DV_II_46_2_bit));
	m[1] &= ((0-(((W[48]^W[55])>>29)&1)) | ~(DV_I_51_0_bit|DV_I_52_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v16_part5(const u32v16 W[65], u32v16 m[4])
{
	m[2] &= ((((W[47]^W[49])&(1<<6))-(1<<6)) | ~(DV_I_49_2_bit|DV_I_51_2_bit));
	m[3] &= ((((W[48]^(W[47]>>5))&(1<<1))-(1<<1)) | ~(DV_I_47_2_bit|DV_II_51_2_bit));
	m[0] &= ((((W[46]^W[48])&(1<<6))-(1<<6)) | ~(DV_I_48_2_bit|DV_I_50_2_bit));
	m[1] &= ((((W[47]^(W[46]>>5))&(1<<1))-(1<<1)) | ~(DV_I_46_2_bit|DV_II_50_2_bit));
	m[2] &= ((0-((W[44]^(W[45]>>5))&(1<<1))) | ~(DV_I_51_2_bit|DV_II_49_2_bit));
	m[3] &= ((((W[43]^W[45])&(1<<6))-(1<<6)) | ~(DV_I_47_2_bit|DV_I_49_2_bit));
	m[0] &= (((((W[42]^W[44])>>6)&1)-1) | ~(DV_I_46_2_bit|DV_I_48_2_bit));
	m[1] &= ((((W[43]^(W[42]>>5))&(1<<1))-(1<<1)) | ~(DV_II_46_2_bit|DV_II_51_2_bit));
	m[2] &= ((((W[42]^(W[41]>>5))&(1<<1))-(1<<1)) | ~(DV_I_51_2_bit|DV_II_50_2_bit));
	m[3] &= ((((W[41]^(W[40]>>5))&(1<<1))-(1<<1)) | ~(DV_I_50_2_bit|DV_II_49_2_bit));
	m[0] &= ((((W[39]^(W[43]>>25))&(1<<4))-(1<<4)) | ~(DV_I_52_0_bit|DV_II_51_0_bit));
	m[1] &= ((((W[38]^(W[42]>>25))&(1<<4))-(1<<4)) | ~(DV_I_51_0_bit|DV_II_50_0_bit));
	m[2] &= ((0-((W[37]^(W[38]>>5))&(1<<1))) | ~(DV_I_48_2_bit|DV_I_51_2_bit));
	m[3] &= ((((W[37]^(W[41]>>25))&(1<<4))-(1<<4)) | ~(DV_I_50_0_bit|DV_II_49_0_bit));
}

SHA1DC_UBC_INLINE void ubc_check_v16_part6(const u32v16 W[65], u32v16 m[4])
{
	m[0] &= ((0-((W[36]^W[38])&(1<<4))) | ~(DV_II_52_0_bit|DV_II_54_0_bit));
	m[1] &= ((0-((W[35]^(W[36]>>5))&(1<<1))) | ~(DV_I_46_2_bit|DV_I_49_2_bit));
	m[2] &= ((((W[35]^(W[39]>>25))&(1<<3))-(1<<3)) | ~(DV_I_51_0_bit|DV_II_47_0_bit));
	{
		u32v16 keep = ((((W[61]^(W[62]>>5))) >> 1) & 1);
		keep &= (((((W[59]^(W[63]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[58]^(W[63]>>30))) >> 0) & 1);
		m[3] &= -keep | ~DV_I_43_0_bit;
	}
	{
		u32v16 keep = ((((W[62]^(W[63]>>5))) >> 1) & 1);
		keep &= (((((W[60]^(W[64]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[59]^(W[64]>>30))) >> 0) & 1);
		m[0] &= -keep | ~DV_I_44_0_bit;
	}
	m[1] &= ((~((W[40]^W[42])>>2)) | ~DV_I_46_2_bit);
	{
		u32v16 keep = ((((W[62]^(W[63]>>5))) >> 2) & 1);
		keep &= (((((W[41]^W[43])) >> 6) & 1) ^ 1);
		m[2] &= -keep | ~DV_I_47_2_bit;
	}
	{
		u32v16 keep = ((((W[63]^(W[64]>>5))) >> 2) & 1);
		keep &= (((((W[48]^(W[49]<<5))) >> 6) & 1) ^ 1);
		m[3] &= -keep | ~DV_I_48_2_bit;
	}
	{
		u32v16 keep = (((((W[49]^(W[50]<<5))) >> 6) & 1) ^ 1);
		keep &= ((((W[42]^W[50])) >> 1) & 1);
		keep &= (((((W[39]^(W[40]<<5))) >> 6) & 1) ^ 1);
		keep &= ((((W[38]^W[40])) >> 1) & 1);
		m[0] &= -keep | ~DV_I_49_2_bit;
	}
	m[1] &= ((((W[36]^W[37])<<7)) | ~DV_I_50_0_bit);
	m[2] &= ((((W[43]^W[51])<<11)) | ~DV_I_50_2_bit);
	m[3] &= ((((W[37]^W[38])<<9)) | ~DV_I_51_0_bit);
	{
		u32v16 keep = (((((W[51]^(W[52]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[49]^W[51])) >> 6) & 1) ^ 1);
		keep &= (((((W[37]^(W[37]>>5))) >> 1) & 1) ^ 1);
		keep &= (((((W[35]^(W[39]>>25))) >> 5) & 1) ^ 1);
		m[0] &= -keep | ~DV_I_51_2_bit;
	}
	m[1] &= ((((W[38]^W[39])<<11)) | ~DV_I_52_0_bit);
}

SHA1DC_UBC_INLINE void ubc_check_v16_part7(const u32v16 W[65], u32v16 m[4])
{
	m[2] &= ((((W[47]^W[51])<<17)) | ~DV_II_46_2_bit);
	{
		u32v16 keep = (((((W[36]^(W[40]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[35]^(W[40]<<2))) >> 30) & 1);
		m[3] &= -keep | ~DV_II_48_0_bit;
	}
	{
		u32v16 keep = (((((W[37]^(W[41]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[36]^(W[41]<<2))) >> 30) & 1);
		m[0] &= -keep | ~DV_II_49_0_bit;
	}
	{
		u32v16 keep = (((((W[53]^(W[54]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[51]^W[53])) >> 6) & 1) ^ 1);
		keep &= ((((W[50]^W[54])) >> 1) & 1);
		keep &= (((((W[45]^(W[46]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[37]^(W[41]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[36]^(W[41]>>30))) >> 0) & 1);
		m[1] &= -keep | ~DV_II_49_2_bit;
	}
	{
		u32v16 keep = ((((W[55]^W[58])) >> 29) & 1);
		keep &= (((((W[38]^(W[42]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[37]^(W[42]<<2))) >> 30) & 1);
		m[2] &= -keep | ~DV_II_50_0_bit;
	}
	{
		u32v16 keep = (((((W[54]^(W[55]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[52]^W[54])) >> 6) & 1) ^ 1);
		keep &= ((((W[51]^W[55])) >> 1) & 1);
		keep &= ((((W[45]^W[47])) >> 1) & 1);
		keep &= (((((W[38]^(W[42]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[37]^(W[42]>>30))) >> 0) & 1);
		m[3] &= -keep | ~DV_II_50_2_bit;
	}
	{
		u32v16 keep = (((((W[39]^(W[43]>>25))) >> 3) & 1) ^ 1);
		keep &= ((((W[38]^(W[43]<<2))) >> 30) & 1);
		m[0] &= -keep | ~DV_II_51_0_bit;
	}
	{
		u32v16 keep = (((((W[55]^(W[56]<<5))) >> 6) & 1) ^ 1);
		keep &= (((((W[53]^W[55])) >> 6) & 1) ^ 1);
		keep &= ((((W[52]^W[56])) >> 1) & 1);
		keep &= ((((W[46]^W[48])) >> 1) & 1);
		keep &= (((((W[39]^(W[43]>>25))) >> 5) & 1) ^ 1);
		keep &= ((((W[38]^(W[43]>>30))) >> 0) & 1);
		m[1] &= -keep | ~DV_II_51_2_bit;
	}
	{
		u32v16 keep = (((((W[59]^W[60])) >> 29) & 1) ^ 1);
		keep &= (((((W[40]^(W[44]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[40]^(W[44]>>25))) >> 4) & 1) ^ 1);
		keep &= ((((W[39]^(W[44]<<2))) >> 30) & 1);
		m[2] &= -keep | ~DV_II_52_0_bit;
	}
	{
		u32v16 keep = ((((W[58]^W[61])) >> 29) & 1);
		keep &= (((((W[57]^(W[61]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[41]^(W[45]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[41]^(W[45]>>25))) >> 4) & 1) ^ 1);
		m[3] &= -keep | ~DV_II_53_0_bit;
	}
	{
		u32v16 keep = (((((W[58]^(W[62]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[42]^(W[46]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[42]^(W[46]>>25))) >> 4) & 1) ^ 1);
		m[0] &= -keep | ~DV_II_54_0_bit;
	}
	{
		u32v16 keep = (((((W[59]^(W[63]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[57]^(W[59]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[43]^(W[47]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[43]^(W[47]>>25))) >> 4) & 1) ^ 1);
		m[1] &= -keep | ~DV_II_55_0_bit;
	}
	{
		u32v16 keep = (((((W[60]^(W[64]>>25))) >> 4) & 1) ^ 1);
		keep &= (((((W[44]^(W[48]>>25))) >> 3) & 1) ^ 1);
		keep &= (((((W[44]^(W[48]>>25))) >> 4) & 1) ^ 1);
		m[2] &= -keep | ~DV_II_56_0_bit;
	}
}

#define UBC_V16_NPARTS 8
#define UBC_V16_EARLYOUT_AFTER_PART 7

SHA1DC_UBC_INLINE void ubc_check_v16_inline(const u32v16 W[65], u32v16 dvmask[1])
{
	u32v16 m[4] = { ~(u32v16){0}, ~(u32v16){0}, ~(u32v16){0}, ~(u32v16){0} };

	ubc_check_v16_part0(W, m);
	ubc_check_v16_part1(W, m);
	ubc_check_v16_part2(W, m);
	ubc_check_v16_part3(W, m);
	ubc_check_v16_part4(W, m);
	ubc_check_v16_part5(W, m);
	ubc_check_v16_part6(W, m);
	m[0] &= m[1] & m[2] & m[3];
	m[1] = m[2] = m[3] = ~(u32v16){0};
	if (ubc_v16_all_zero(&m[0])) { dvmask[0] = m[0]; return; }
	ubc_check_v16_part7(W, m);
	dvmask[0] = m[0] & m[1] & m[2] & m[3];
}
#endif /* UBC_CHECK_V16_H */
#endif /* SHA1DC_UBC_CHECK_SIMD_H */
